//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ILoginDto
{
	login: string;
	password: string;
}
export interface IAccecTokenDto
{
	value: string;
}
export interface IEditIssueDto
{
	id: number;
	title: string;
	notes: string;
	state: IssueState;
	isUrgent: boolean;
	deadline: string;
	assignedToId: number;
}
export interface IIssueDto
{
	id: number;
	title: string;
	notes: string;
	state: IssueState;
	isUrgent: boolean;
	deadline: string;
	assignedToId: number;
	assignedPersonDisplayName: string;
}
export interface IPersonSelectDto
{
	id: number;
	displayName: string;
}
export enum IssueState {
	Todo = 0,
	Doing = 1,
	Done = 2
}
