//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ILoginDto
{
	login: string;
	password: string;
}
export interface IAccecTokenDto
{
	value: string;
}
export enum IssueState {
	Todo = 0,
	Doing = 1,
	Done = 2
}
